### ISSUE TITLE
Force my OnePlus 11 to High Resolution (1080x2412)

### ISSUE THREAD

**Issue by MrkElmdor** [chenzyadb/CuRefreshRateTuner#2]
Once I update the module to latest and reboot it lower device display to High Res from Full Res (1440x3216)
Going into settings and try to change the display won't work. I had to roll back to previous version and it's working fine.
Device: OP11 5G CPH2451 running latest LinageOS 21 A14 Apatched

**Comment by chenzyadb** [comment]
I don't have a device that supports high resolution, so I'm not sure where the issue lies. If you can provide the output of `adb shell dumpsys display`, I can try to fix the problem.

**Comment by ixaobao** [comment]
我的iqoo9p也有同样的问题，安装模块后没有正确识别分辨率，我1440分辨率，配置文件resolution值为1080，导致开机后强制改为1080分辨率，手动修改为1440后重启正常，应该是识别错误，看log有太多id，导致错误识别
![微信图片_20240701033120](https://github.com/chenzyadb/CuRefreshRateTuner/assets/116019804/2df18bb8-4987-4947-a685-9738c13108c3)
![微信图片_20240701033130](https://github.com/chenzyadb/CuRefreshRateTuner/assets/116019804/6922b146-4f93-4283-ad78-ed1f7f9debc5)

**Comment by chenzyadb** [comment]
> 我的iqoo9p也有同样的问题，安装模块后没有正确识别分辨率，我1440分辨率，配置文件resolution值为1080，导致开机后强制改为1080分辨率，手动修改为1440后重启正常，应该是识别错误，看log有太多id，导致错误识别
> ![微信图片_20240701033120](https://github.com/chenzyadb/CuRefreshRateTuner/assets/116019804/2df18bb8-4987-4947-a685-9738c13108c3)
> ![微信图片_20240701033130](https://github.com/chenzyadb/CuRefreshRateTuner/assets/116019804/6922b146-4f93-4283-ad78-ed1f7f9debc5)
> 

这个配置文件就是需要手动修改的，每个手机的参数都不一样，每个人的需求也不一样，不可能默认就提供修改后的配置文件的😂

**Comment by ixaobao** [comment]
搞个自动识别当前分辨率好些吧，不然安装重启就这样，免不得以为模块有问题。

**Comment by ixaobao** [comment]
搞个自动识别当前分辨率好些吧，不然安装重启就这样，免不得以为模块有问题。

**Comment by ixaobao** [comment]
或者安装时手动选择分辨率也比较方便
