### ISSUE TITLE
Is it possible to go through full LTPO range?

### ISSUE THREAD

**Issue by hir0xygen** [chenzyadb/CuRefreshRateTuner#4]
It's working perfectly fine to force 60 Hz when inactive and 120 Hz when active on my OnePlus 10 Pro, however I'm unable to force anything lower, for example 5 Hz when inactive.
Is there a way to achieve this?
The display supports 1–120 Hz

**Comment by chenzyadb** [comment]
Adjusting the refresh rate to below 60Hz necessitates the system to offer a compatible DisplayMode. Currently, the project solely relies on touch input to determine its active state. However, implementing LTPO technology, which dynamically adjusts the refresh rate based on the presence of new rendering frames, poses a challenge as the project currently lacks the capability to detect such rendering activities, thus hindering the achievement of extremely low refresh rates.
