### ISSUE TITLE
Unable to install through Magisk

### ISSUE THREAD

**Issue by DrSaad77** [chenzyadb/CuRefreshRateTuner#5]
I dont understand why when I try to install this module through Magisk, it always end with failure!
Magisk 28.
But I managed to install it through MMRL app, it is disturbing me, why it do not install through Magisk, though it is a magisk Module.
How can I install it through Magisk without to use an module Manager ??
PS: I tried the Magisk.zip

**Comment by chenzyadb** [comment]
Maybe there is a problem with the installation script; it is currently only compatible with Magisk 27.0. I haven't tested whether it works on newer versions of Magisk yet. The next version will fix this issue.
